/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_wute_lib1_MyClass */

#ifndef _Included_com_wute_lib1_MyClass
#define _Included_com_wute_lib1_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wute_lib1_MyClass
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
	JNIEXPORT void JNICALL Java_com_wute_lib1_MyClass_bsdiff
		(JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
